#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONF_DIR="${DIR}"/..

DEVICE=$(hostname -s)

case $(uname) in

  "Linux")
    echo "Performing setup for linux"
    $DIR/setup-linux
    ;;

  "Darwin")
    echo "Performing setup for MacOS"
    $DIR/setup-macos
    ;;
esac

if [ ! -d "${CONF_DIR}/fonts" ]; then
  echo "Installing powerline fonts"
  git clone https://github.com/powerline/fonts
  cd fonts
  ./install.sh
  cd ..
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

ZSH_CUSTOM_DIR="$HOME/.oh-my-zsh/custom"
echo "Setting up oh-my-zsh/custom"
if [ -d "$ZSH_CUSTOM_DIR" ]; then
  echo "Copying existing oh-my-zsh/custom"
  shopt -s dotglob
  cp -r -i $ZSH_CUSTOM_DIR/* "$CONF_DIR/oh-my-zsh/custom/"
  shopt -u dotglob
  rm -ri "$ZSH_CUSTOM_DIR/"
fi

ln -sfn "$CONF_DIR/oh-my-zsh/custom" "$ZSH_CUSTOM_DIR"

if [ ! -d "$ZSH_CUSTOM_DIR/plugins/zsh-syntax-highlighting" ]; then
  echo "Installing zsh syntax highlighting"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

ZSH_THEME_FILE="$CONF_DIR/zsh-theme"
if [ ! -f "$ZSH_THEME_FILE" ]; then
  DEFAULT_ZSH_THEME="clean"
  echo "Setting zsh theme in $ZSH_THEME_FILE to: $DEFAULT_ZSH_THEME"
  echo -n $DEFAULT_ZSH_THEME > $CONF_DIR/zsh-theme
fi
ln -s $CONF_DIR/zsh-theme $HOME/.zsh-theme

echo "Symlinking dotfiles to $HOME"

device_zshrc="$CONF_DIR/zshrc.$DEVICE"
touch -a device_zshrc
echo "Created $device_zshrc. Edit this file for device-specific config."

ln -sfn $CONF_DIR/.vimrc $HOME/.vimrc
ln -sfn $CONF_DIR/.tmux.conf $HOME/.tmux.conf
ln -sfn $CONF_DIR/.Xresources $HOME/.Xresources
ln -sfn $CONF_DIR/.zshrc $HOME/.zshrc
ln -sfn device_zshrc "$HOME/.zshrc.local"
ln -sfn "${CONF_DIR}/nvim" $HOME/.config/nvim

echo "Installing vim-plug to ~/.local/share/nvim/site/autoload/plug.vim"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Compiling terminfo file"

tic -x $CONF_DIR/tmux-256color.terminfo

echo "For tmux themeing, run: ./util/tmux-theme"
echo "For device-specific zsh settings, edit zshrc.$DEVICE"

